# Site
repository: sproogen/resume-theme
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: Charles Claude Reginald Dennis
title: |
  Chartered Global Management Accountant [CGMA]
email: charles.dennis2@gmail.com
website: https://cdennis12280.github.io/
location: Northampton, UK # Adding location to personal info

# Dark Mode (true/false/never)
darkmode: false

# Social links
#twitter_username: facespics
github_username:  cdennis12280
# stackoverflow_username: "00000001"
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
# instagram_username: jameswgran
# linkedin_username: jameswgrant
# xing_username: jekyll
# pinterest_username: jekyll
# youtube_username: globalmtb
# googleplus_username: +jekyll
# orcid_username: 0000-0000-0000-0000

# Additional icon links
additional_links:
- title: risk.net
  icon: fas fa-globe
  url: https://www.risk.net
# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&m=free)
#   url: Link url (eg. https://google.com)


### Need to get this working ####

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
gtag: "G-TDRPKY7HX0"
# google_analytics: "UA-00000000-0"

############################################

# About Section
# about_title: About Me
about_profile_image: images/profile.jpg
about_content: | # this will include new lines to allow paragraphs
  Hi, I’m Charles, a Chartered Global Management Accountant with a solid foundation in financial analysis and reporting. Over the course of my career, I’ve developed expertise in financial modeling, data analysis, and auditing. I’m a driven and results-focused professional with a track record of streamlining financial processes, enhancing reporting accuracy, and providing strategic business advice. I’m excited about applying my skills and experience to a challenging role where I can deliver meaningful impact.

  Let’s connect to discuss how my expertise can align with your organisation’s goals.

  Key skills I have to help improve your market capital, share price and improve efficiency: 
  
  <mark>Financial analysis</mark> - expertly interpreting complex financial data to optimise performance and inform strategic decision-making.
  
  <mark>Budgeting and forecasting</mark> - developing precise financial plans and delivering insightful forecasts to support organisational objectives.
  
  <mark>Power BI dashboard creation</mark> - designing sophisticated, interactive dashboards that transform data into actionable insights.
  
  <mark>Python</mark> - leveraging advanced programming skills to automate processes and create innovative financial models.
  
  <mark>SQL</mark> - crafting and executing efficient queries to extract, manipulate, and analyse critical data with precision.
  
  <mark>Generative AI</mark> - applying cutting-edge machine learning techniques to streamline operations and unlock new insights.
  
  <mark>Large language models (LLMs)</mark> - harnessing the potential of AI for natural language processing and enhanced decision support.
  
  <mark>Risk identification and assessment</mark> - systematically evaluating and prioritising risks to safeguard business operations and objectives.
  
  <mark>Predictive analytics</mark> - utilising statistical models to anticipate trends and proactively inform strategy.
  
  <mark>Data visualisation</mark> - producing clear, impactful visuals to communicate complex datasets effectively.
  
  <mark>Financial modelling</mark> - constructing robust models to evaluate scenarios, forecast performance, and inform critical decisions.
  
  <mark>Variance analysis</mark> - meticulously identifying and explaining deviations to uncover trends and improve accuracy.
  
  <mark>Risk mitigation</mark> - devising comprehensive strategies to reduce risk exposure and enhance organisational resilience.
  
  <mark>Scenario planning</mark> - conducting detailed analyses of potential outcomes to strengthen strategic foresight.
  
  <mark>Internal controls and governance</mark> - establishing rigorous frameworks to uphold data integrity and ensure regulatory compliance.
  
  <mark>Stakeholder reporting</mark> - delivering compelling reports that influence decisions and build stakeholder confidence.
  
  <mark>KPIs and metrics development</mark> - defining and tracking key performance indicators to drive success and accountability.
  
  <mark>Data mining</mark> - uncovering valuable insights from vast datasets to inform high-level decision-making.
  
  <mark>Regulatory compliance</mark> - ensuring all financial and operational activities align with stringent legal and policy requirements.

content:
  - title: Projects # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: top-middle
        title: CCRD Pilot
        link: github.com/cdennis12280
        # link_text: Project Website
        additional_links:
          - title:  cdennis12280/CCRD-Pilot
            icon: fab fa-github
            url: github.com/cdennis12280
          # - title:  Github page for project (eg. sproogen/modern-resume-theme)
          #   icon: fab fa-github
          #   url: Link to project (eg. sproogen.github.io/modern-resume-theme)
        quote: >
          Currently, openpilot performs the functions of Adaptive Cruise Control (ACC) and Automated Lane Centering (ALC). openpilot can accelerate, brake automatically for other vehicles, and steer to follow the road/lane.
        description: | # this will include new lines to allow paragraphs
          This project is a fork of Openpilot, with custom tweaks and advancements to enable Automated Lane Centering (ALC) and Adaptive Cruise Control (ACC).

  - title: Experience # Title for the section
    layout: list # Type of content section (list/text)
    content:
      
      - layout: left
        title: Notary Northampton
        link: https://notarynorthampton.co.uk/
        # link_text: https://notarynorthampton.co.uk/
        sub_title: Head of Finance and Strategy
        caption: April 2023 - Present
        quote: >
          To provide expert verification and authentication of documents for international and commercial transactions, ensuring integrity and compliance while supporting clients with professionalism and precision. 
        description: | # this will include new lines to allow paragraphs
            I am responsible for maintaining a robust and effective control environment that ensures financial accuracy, compliance, and integrity across all operations. In my role, I drive transformation within operational finance, focusing on automating processes to enhance efficiency, reduce manual intervention, and increase the speed and reliability of financial workflows. I deliver high-quality management information and actionable insights through advanced forecasting techniques to support strategic decision-making.

            I lead the development of a best-in-class finance function by implementing innovative practices, fostering a culture of continuous improvement, and aligning the team’s efforts with the organisation’s growth objectives. My approach is proactive, identifying and addressing inefficiencies, optimising financial systems, and ensuring my team has the tools and skills necessary to meet evolving business demands. I work closely with senior leadership to shape financial strategies, ensuring alignment with the company’s vision and long-term goals.

      - layout: left
        title: West Northampton Council
        link: https://www.westnorthants.gov.uk/
        # link_text: https://www.westnorthants.gov.uk/
        sub_title: Finance Business Partner
        caption: May 2023 - Present
        quote: >
          West Northamptonshire Council's mission is to make West Northants a great place to live, work, visit, and thrive. 
        description: | # this will include new lines to allow paragraphs
            The Finance Business Partner plays a pivotal role in delivering strategic, high-caliber financial support to senior leadership, including Directors and Heads of Service, ensuring robust financial governance and regulatory compliance. This high-profile position encompasses leadership in financial planning, budget modeling, risk analysis, and the development of innovative processes to enhance operational efficiency and align financial practices with the council's strategic objectives. The role also entails managing and developing a team of finance professionals, fostering a culture of excellence, and providing targeted training to improve financial acumen across the organization. Furthermore, the Finance Business Partner is instrumental in the production of the Medium Term Financial Plan (MTFP), the Capital Strategy, and the delivery of timely, accurate financial reporting, driving the council’s commitment to exceptional financial stewardship
      
      - layout: left
        title: Network Rail
        link: https://www.networkrail.co.uk/
        # link_text: https://www.networkrail.co.uk/
        sub_title: Finance Business Partner
        caption: December 2018 - April 2023
        quote: >
          Network Rail's mission is to "put passengers first," aiming to become a company that is on the side of passengers and freight users; that is easy to engage with and is an efficient and dependable partner; a company people are proud to work for; instinctively recognised as an industry leader.
        description: | # this will include new lines to allow paragraphs
             I led assurance reviews for capital projects exceeding £500m, ensuring alignment with corporate and regulatory frameworks, built and maintained Power BI dashboards for financial performance visualization, and prepared high-quality reports influencing regulatory and stakeholder decisions, while identifying efficiency improvements, implementing cost-saving measures, and enhancing internal processes; I also conducted audits for compliance, collaborated with cross-functional teams to align project delivery with budgets, strengthened risk management practices through governance frameworks, and championed continuous improvement initiatives that drove measurable process optimization and results.

      - layout: left
        title: NHS
        link: https://www.nhs.uk/
        # link_text: https://www.nhs.uk/
        sub_title: Surge and Escalation Intelligence Officer
        caption: July 2017 - December 2018
        quote: >          
          The NHS's mission is to provide comprehensive, high-quality, patient-centered healthcare that is accessible to all, based on clinical need, while upholding principles of excellence, professionalism, and accountability.
        description: | # this will include new lines to allow paragraphs
             Implementation of a surge management and resilience system for the NHS in Northamptonshire, overseeing the monitoring of providers' progress on Urgent Care and Surge Management plans, ensuring timely reporting to NHS England and the CCG, sharing best practices for continuous improvement, managing risk processes, and ensuring robust control systems for data integrity, functionality, and governance.


      - layout: left
        title: National Grid
        link: https://www.nationalgrid.com/
        # link_text: https://www.nationalgrid.com/
        sub_title: National Grid – System Performance Officer
        caption: April 2009 - August 2016
        quote: >
          National Grid's mission is to be at the heart of a clean, fair, and affordable energy future, demonstrating their contribution to society by enabling the energy transition for all, tackling climate change, and ensuring no one is left behind.
        description: | # this will include new lines to allow paragraphs
            The role involved managing IT infrastructure and Salesforce systems, overseeing configuration and deployment for optimal performance, delivering Salesforce training, conducting quality assurance reviews for audits, analyzing operational data to drive workflow improvements, creating customized dashboards and automated reports, collaborating with external stakeholders on system issues, managing IS budgets, negotiating contracts for cost savings, and leading system upgrades while implementing best practices for data management and governance.


  - title: Education # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: AICPA & CIMA
        sub_title: Chartered Global Management Accountant
        quote: >
          The American Institute of CPAs® (AICPA) and its predecessors have served the public interest for 137 years. The Chartered Institute of Management Accountants® (CIMA) was founded in 1919 and has helped shaped the profession for over a century. In 2017, they came together as AICPA & CIMA to forge a powerful international alliance that promotes accounting and finance in every corner of the world.
        description: | # this will include new lines to allow paragraphs
          Becoming a Chartered Global Management Accountant has been an invaluable journey that has significantly enhanced my expertise in strategic financial management, business performance analysis, and risk management. Through this process, I’ve developed a strong ability to interpret complex financial data, streamline processes, and deliver actionable insights that support sound decision-making and drive business success.

          Beyond technical proficiency, the qualification has also strengthened my leadership and problem-solving skills, enabling me to thrive in dynamic and challenging environments. It’s given me a deeper understanding of the bigger picture, allowing me to align financial strategy with broader business objectives and make a tangible impact on organizational growth.
      
      - layout: left
        sub_title: Advanced Diploma in Management Accounting (Adv Dip MA)
        description: | # this will include new lines to allow paragraphs
          Successfully achieved the CIMA Advanced Diploma in Management Accounting, a qualification equivalent to a bachelor’s degree, showcasing advanced proficiency in financial management, strategic planning, and business performance analysis. This achievement demonstrates my expertise in cost control, budgeting, risk management, and strategic decision-making, all critical to driving operational and organisational success. It has equipped me with the ability to interpret and analyse complex financial data, provide valuable insights to support high-level business decisions, and ensure full compliance with regulatory standards.

      - layout: left
        sub_title: Diploma in Management Accounting (Dip MA)
        description: | # this will include new lines to allow paragraphs
          Successfully achieved the CIMA Diploma in Management Accounting, a qualification equivalent to the first year of a bachelor’s degree, demonstrating a strong foundation in management accounting and financial decision-making. This accomplishment highlights my skills in cost management, budgeting, financial reporting, and performance evaluation. It has equipped me with the knowledge to interpret financial data, support effective decision-making processes, and contribute to the operational success of an organisation.




  - title: Certifications # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        sub_title: Professional Certifications
        description: | # this will include new lines to allow paragraphs
          I hold specific certifications in the following specialisms:
          - **Corporate Finance Strategy** - Expertise in aligning financial operations with corporate goals.
          - **Strategy Management** - Advanced skills in implementing and overseeing strategic plans.
          - **Enterprise Risk Management** - Proficiency in identifying, assessing, and mitigating risks.
          - **Digital Finance** - Knowledge of emerging technologies transforming financial processes.
          - **Budget and Cost Analysis** - Skilled in optimizing budgets and controlling costs.
          - **Financial Reporting** - Excellence in producing accurate and compliant reports.
          - **Team Performance Management** - Proven ability to lead and enhance team efficiency.
          - **Financial Planning and Analysis** - Expertise in forecasting and analyzing financial performance.
          - **Financial Statement Analysis** - Strong ability to interpret and derive insights from financial statements.


  - title: A Little More About Me
    layout: text
    content: | # this will include new lines to allow paragraphs
      Alongside my interests in financial derivatives and strategic finance some of my other interests and hobbies are:
      - Artificial Intelligence (You can find out more on my github account)
      - Data-Driven Decision-Making
      - Mountain Biking
      - Gaming
      - Keeping fit

# Footer
footer_show_references: true
# references_title: References on request (Override references text)

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag

footer: | 
  © 2024 Charles Dennis. All Rights Reserved.