# Site
repository: sproogen/resume-theme
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: Charles Claude Reginald Dennis
title: Chartered Global Management Accountant [CGMA]
email: charles.dennis2@gmail.com
website: https://cdennis12280.github.io/

# Dark Mode (true/false/never)
darkmode: false

# Social links
#twitter_username: facespics
github_username:  cdennis12280
# stackoverflow_username: "00000001"
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
# instagram_username: jameswgran
# linkedin_username: jameswgrant
# xing_username: jekyll
# pinterest_username: jekyll
# youtube_username: globalmtb
# googleplus_username: +jekyll
# orcid_username: 0000-0000-0000-0000

# Additional icon links
additional_links:
- title: risk.net
  icon: fas fa-globe
  url: https://www.risk.net
# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&m=free)
#   url: Link url (eg. https://google.com)


### Need to get this working ####

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
gtag: "G-TDRPKY7HX0"
# google_analytics: "UA-00000000-0"

############################################

# About Section
# about_title: About Me
about_profile_image: images/profile.jpg
about_content: | # this will include new lines to allow paragraphs
  Hi, I’m Charles, a CGMA-qualified accountant with a solid foundation in financial analysis and reporting. Over the course of my career, I’ve developed expertise in financial modeling, data analysis, and auditing. I’m a driven and results-focused professional with a track record of streamlining financial processes, enhancing reporting accuracy, and providing strategic business advice. I’m excited about applying my skills and experience to a challenging role where I can deliver meaningful impact.

  I am most skilled in: <mark>Strategic reporting</mark>, <mark>Financial data analysis</mark> and <mark>PowerBI dashboard development</mark>

content:
  - title: Projects # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: top-middle
        title: Super awesome project
        link: github.com/sproogen
        # link_text: Project Website
        additional_links:
          - title:  sproogen/modern-resume-theme
            icon: fab fa-github
            url: github.com/sproogen/modern-resume-theme
          # - title:  Github page for project (eg. sproogen/modern-resume-theme)
          #   icon: fab fa-github
          #   url: Link to project (eg. sproogen.github.io/modern-resume-theme)
        quote: >
          This is probably one of the greatest apps ever created, if you don't agree you're probably wrong.
        description: | # this will include new lines to allow paragraphs
          I started this project as a way if learning <mark>React</mark> and it has since grown into a fully fledged app. I have learned many skills through this and been I'm very proud of having this in my portfolio. If you don't have a project as awesome as this I would advise you make one.

  - title: Experience # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: West Northampton Council
        link: https://www.westnorthants.gov.uk/
        # link_text: https://www.westnorthants.gov.uk/
        sub_title: Finance Business Partner
        caption: May 2023 - Present
        quote: >
          West Northamptonshire Council's mission is to make West Northants a great place to live, work, visit, and thrive. 
        description: | # this will include new lines to allow paragraphs
            The Finance Business Partner plays a pivotal role in delivering strategic, high-caliber financial support to senior leadership, including Directors and Heads of Service, ensuring robust financial governance and regulatory compliance. This high-profile position encompasses leadership in financial planning, budget modeling, risk analysis, and the development of innovative processes to enhance operational efficiency and align financial practices with the council's strategic objectives. The role also entails managing and developing a team of finance professionals, fostering a culture of excellence, and providing targeted training to improve financial acumen across the organization. Furthermore, the Finance Business Partner is instrumental in the production of the Medium Term Financial Plan (MTFP), the Capital Strategy, and the delivery of timely, accurate financial reporting, driving the council’s commitment to exceptional financial stewardship
      
      - layout: left
        title: The Boring Company
        link: boringcompany.com
        # link_text: boringcompany.com
        sub_title: Senior Network System Administrator
        caption: November 2017 - Present
        quote: >
          Solving 21st century problems by diging holes and making game changing products like the *not a flamethrower*
        description: | # this will include new lines to allow paragraphs
            Every company needs its networks properly administered and The Boring Compay is no exception. Digging holes is hard and I play my part making sure the whole company stays connected. I lead a team of 5 people and enjoy driving the company to try new technologies.

      - layout: left
        title: The Boring Company
        link: boringcompany.com
        # link_text: boringcompany.com
        sub_title: Senior Network System Administrator
        caption: November 2017 - Present
        quote: >
          Solving 21st century problems by diging holes and making game changing products like the *not a flamethrower*
        description: | # this will include new lines to allow paragraphs
            Every company needs its networks properly administered and The Boring Compay is no exception. Digging holes is hard and I play my part making sure the whole company stays connected. I lead a team of 5 people and enjoy driving the company to try new technologies.


      - layout: left
        title: The Boring Company
        link: boringcompany.com
        # link_text: boringcompany.com
        sub_title: Senior Network System Administrator
        caption: November 2017 - Present
        quote: >
          Solving 21st century problems by diging holes and making game changing products like the *not a flamethrower*
        description: | # this will include new lines to allow paragraphs
            Every company needs its networks properly administered and The Boring Compay is no exception. Digging holes is hard and I play my part making sure the whole company stays connected. I lead a team of 5 people and enjoy driving the company to try new technologies.


      - layout: left
        title: The Boring Company
        link: boringcompany.com
        # link_text: boringcompany.com
        sub_title: Senior Network System Administrator
        caption: November 2017 - Present
        quote: >
          Solving 21st century problems by diging holes and making game changing products like the *not a flamethrower*
        description: | # this will include new lines to allow paragraphs
            Every company needs its networks properly administered and The Boring Compay is no exception. Digging holes is hard and I play my part making sure the whole company stays connected. I lead a team of 5 people and enjoy driving the company to try new technologies.









  - title: Education # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: AICPA & CIMA
        sub_title: Chartered Global Management Accountant
        quote: >
          The American Institute of CPAs® (AICPA) and its predecessors have served the public interest for 137 years. The Chartered Institute of Management Accountants® (CIMA) was founded in 1919 and has helped shaped the profession for over a century. In 2017, they came together as AICPA & CIMA to forge a powerful international alliance that promotes accounting and finance in every corner of the world.
        description: | # this will include new lines to allow paragraphs
          Becoming a CGMA has been an invaluable journey that has significantly enhanced my expertise in strategic financial management, business performance analysis, and risk management. Through this process, I’ve developed a strong ability to interpret complex financial data, streamline processes, and deliver actionable insights that support sound decision-making and drive business success.

          Beyond technical proficiency, the qualification has also strengthened my leadership and problem-solving skills, enabling me to thrive in dynamic and challenging environments. It’s given me a deeper understanding of the bigger picture, allowing me to align financial strategy with broader business objectives and make a tangible impact on organizational growth.

  - title: A Little More About Me
    layout: text
    content: | # this will include new lines to allow paragraphs
      Alongside my interests in financial derivatives and strategic finance some of my other interests and hobbies are:
      - Artificial Intelligence (You can find out more on my github account)
      - Data-Driven Decision-Making
      - Mountain Biking
      - Gaming
      - Keeping fit

# Footer
footer_show_references: true
# references_title: References on request (Override references text)

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
